runtime: python37

default_expiration: "4d 5h"

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/png

- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto